# Generated by Django 4.2.3 on 2023-07-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
